version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: verbum_db
      MYSQLD__HOST_CACHE_SIZE: "0"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

volumes:
  dbdata:
